spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/FrancoRaspo/ecommerce-config-server-properties
          clone-on-start: true
          default-label: main
          username: francoraspo@gmail.com
          password: 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
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888


